# Generated by Django 5.0.6 on 2024-05-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('user_password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
